[package]
name = "gt-tracker-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.22"
scraper = "0.19.1"
ureq = "2.10.0"
